// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

use std::fs;
use std::path::Path;

use regex::{Regex, RegexBuilder};

use crate::common::{self, LintIssue};

pub fn run(files: &[String], linter: &str, root: &str) {
    // mingw-headers.txt is generated by:
    //   cd mingw-w64/mingw-w64-headers &&
    //   find . -name "*.h" | xargs -I bob -- basename bob | sort | uniq
    let headers_path = Path::new(root).join("tools/lint/cpp/mingw-headers.txt");
    let Ok(content) = fs::read_to_string(&headers_path) else {
        eprintln!("Warning: could not load mingw-headers.txt");
        return;
    };
    let headers: Vec<&str> = content.lines().filter(|l| !l.is_empty()).collect();
    if headers.is_empty() {
        return;
    }

    let pattern = format!(r"^\s*#\s*include\s*<({})>", headers.join("|"));
    let Ok(case_sensitive) = Regex::new(&pattern) else {
        eprintln!("Error building case-sensitive regex for mingw-capitalization");
        return;
    };
    let Ok(case_insensitive) = RegexBuilder::new(&pattern).case_insensitive(true).build() else {
        eprintln!("Error building case-insensitive regex for mingw-capitalization");
        return;
    };

    common::par_map_lint(files, |path| {
        check_file(path, &case_sensitive, &case_insensitive, linter)
    });
}

fn check_file(
    path: &str,
    case_sensitive: &Regex,
    case_insensitive: &Regex,
    linter: &str,
) -> Vec<LintIssue> {
    let Ok(content) = fs::read_to_string(path) else {
        return Vec::new();
    };

    let mut issues = Vec::new();
    for (lineno, line) in content.lines().enumerate() {
        // Matches a known MinGW header case-insensitively but not with the
        // correct (lowercase) casing — the include will break MinGW builds.
        if case_insensitive.is_match(line) && !case_sensitive.is_match(line) {
            issues.push(LintIssue::error(
                path,
                Some(lineno + 1),
                "A Windows include file is not lowercase, and may break the MinGW build"
                    .to_string(),
                linter,
            ));
        }
    }
    issues
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_correct_include() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join("test.cpp");
        std::fs::write(&file_path, "#include <windows.h>\nint main() {}\n").unwrap();

        let cs = Regex::new(r"^\s*#\s*include\s*<(windows\.h)>").unwrap();
        let ci = RegexBuilder::new(r"^\s*#\s*include\s*<(windows\.h)>")
            .case_insensitive(true)
            .build()
            .unwrap();

        let issues = check_file(file_path.to_str().unwrap(), &cs, &ci, "mingw-cap");
        assert!(issues.is_empty());
    }

    #[test]
    fn test_wrong_capitalization() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join("test.cpp");
        std::fs::write(&file_path, "#include <Windows.h>\nint main() {}\n").unwrap();

        let cs = Regex::new(r"^\s*#\s*include\s*<(windows\.h)>").unwrap();
        let ci = RegexBuilder::new(r"^\s*#\s*include\s*<(windows\.h)>")
            .case_insensitive(true)
            .build()
            .unwrap();

        let issues = check_file(file_path.to_str().unwrap(), &cs, &ci, "mingw-cap");
        assert_eq!(issues.len(), 1);
        assert!(issues[0].message.contains("not lowercase"));
    }

    #[test]
    fn test_unrelated_include() {
        let dir = tempfile::tempdir().unwrap();
        let file_path = dir.path().join("test.cpp");
        std::fs::write(&file_path, "#include <stdio.h>\n").unwrap();

        let cs = Regex::new(r"^\s*#\s*include\s*<(windows\.h)>").unwrap();
        let ci = RegexBuilder::new(r"^\s*#\s*include\s*<(windows\.h)>")
            .case_insensitive(true)
            .build()
            .unwrap();

        let issues = check_file(file_path.to_str().unwrap(), &cs, &ci, "mingw-cap");
        assert!(issues.is_empty());
    }
}
